# general:
mode: analyze_cost
techdata_dir: 'data/tech/basic/'
techdata_files:
- basic_chemicals
- cement
- glass_and_ceramics
- other_industries
- steel
- steel_dri
- polymers
projects_file: 'config/projects_polymers.csv'
do_overwrite_project_start_year: True
project_start_year_overwrite: 2025
ccfd_duration: 20
default_wacc: 0.06

#output
show_figures: True
show_figs_in_browser: False
output_dir: 'output/'
save_figures: True
crop_figures: True

# scenarios
scenarios_dir: 'data/scenarios/basic/'
scenarios_actual:
  free_allocations: ''
  prices:
    Electricity: '100 steady'
    CO2: 'PIKExpertGuess-CO2'
    Natural Gas: '40 steady'
    Hydrogen: 'ISI: best-guess'
    Coking Coal: '100 steady'
    Injection Coal: '70 steady'
    Iron Ore: 'Eisenerz Agora'
    Scrap Steel: 'Zero_Dummy_Scrap'
    DRI-Pellets: 'DRI-Pellets Agora'
    Naphta: 'Naphtha a)'
    PCW: 'ExpertGuess-PCW'
